<Project>
  <Target Name="BuildContent" BeforeTargets="BeforeCompile">
    <MSBuild Projects="$(MSBuildThisFileDirectory)MGNamespace.csproj" Targets="Build" RemoveProperties="Configuration;TargetFramework;RuntimeIdentifier;RuntimeIdentifiers">
      <Output TaskParameter="TargetOutputs" ItemName="_ContentBuilderAssembly" />
    </MSBuild>
    <PropertyGroup>
      <ContentOutput>$([System.IO.Path]::TrimEndingDirectorySeparator($([System.IO.Path]::Combine('$(ProjectDir)', '$(OutputPath)'))))</ContentOutput>
      <ContentTemp>$([System.IO.Path]::TrimEndingDirectorySeparator($([System.IO.Path]::Combine('$(ProjectDir)', '$(IntermediateOutputPath)'))))</ContentTemp>
      <ContentArgs>build -p $(MonoGamePlatform) -s MGNamespace/Assets -o &quot;$(ContentOutput)&quot; -i &quot;$(ContentTemp)&quot;</ContentArgs>
      <ContentCommand>@(_ContentBuilderAssembly->'%(RootDir)%(Directory)%(Filename)')</ContentCommand>
    </PropertyGroup>
    <Exec Command="&quot;$(ContentCommand)&quot; $(ContentArgs)" WorkingDirectory="$(MSBuildThisFileDirectory)..\" CustomErrorRegularExpression="\[E\] .+" CustomWarningRegularExpression="\[W\] .+" />
   </Target>
  <Target Name="AddGeneratedContentAssets"
    AfterTargets="BuildContent">
    <ItemGroup>
      <GeneratedAsset Include="$([System.IO.Path]::Combine('$(ProjectDir)', '$(OutputPath)'))Content\**\*" />

      <AndroidAsset Include="@(GeneratedAsset)"
        Condition="'$(MonoGamePlatform)' == 'Android'">
        <Link>Content\%(GeneratedAsset.RecursiveDir)%(GeneratedAsset.Filename)%(GeneratedAsset.Extension)</Link>
      </AndroidAsset>

      <BundleResource Include="@(GeneratedAsset)"
        Condition="'$(MonoGamePlatform)' == 'MacOSX' Or '$(MonoGamePlatform)' == 'iOS'">
        <Link>Content\%(GeneratedAsset.RecursiveDir)%(GeneratedAsset.Filename)%(GeneratedAsset.Extension)</Link>
      </BundleResource>
    </ItemGroup>
  </Target>
</Project>
