name: Visual Studio Project Templates
env:
  TEMPLATE_VERSION: 3.8.4.1

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-vscode:
    runs-on: windows-latest
    name: Build Templates
    
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v4
      with:
        path: main
        submodules: true

    - name: Setup .NET 8.0.x & 9.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          8.0.x
          9.0.x

    - name: Build and Pack the Templates into a NUGET
      id: MG-Templates
      run: dotnet pack main/CSharp/MonoGame.Templates.CSharp.csproj -p:Configuration=Release /p:Version=${{ ENV.TEMPLATE_VERSION }}

    - name: Upload Template Nugets
      uses: actions/upload-artifact@v4
      with:
        name: MonoGame.Templates.CSharp.${{ ENV.TEMPLATE_VERSION }}
        path: 'Artifacts/MonoGame.Templates.CSharp/**/*.nupkg'

  test-templates:
    needs: [ build-vscode ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, windows-latest, macos-15]
        template:
          - { id: mgdesktopgl, name: DesktopGL, short: mgdesktopgl, project: mgdesktopgl1.csproj, folder: mgdesktopgl1, run: true }
          - { id: mgwindowsdx, name: WindowsDX, short: mgwindowsdx, project: mgwindowsdx1.csproj, folder: mgwindowsdx1, run: true }
          - { id: mgpipeline, name: MonoGame Content Pipeline Extension, short: mgpipeline, project: mgpipeline1.csproj, folder: mgpipeline1, run: false }
          - { id: mglib, name: Library, short: mglib, project: mglib1.csproj, folder: mglib1, run: false }
          - { id: mgcb, name: MGCB, short: mgcb, project: mgcb1.csproj, folder: mgcb1, run: false }
          - { id: mg2dstartkit, name: MonoGame 2D StartKit, short: mg2dstartkit, project: mg2dstartkit1.csproj, folder: mg2dstartkit1, run: true, args: '--targetPlatform linux' }
          - { id: mgblank2dstartkit, name: MonoGame Blank 2D StartKit, short: mgblank2dstartkit, project: mgblank2dstartkit1.csproj, folder: mgblank2dstartkit1, run: true }
          - { id: mgblankmgcbstartkit, name: MonoGame Blank MGCB 2D StartKit, short: mgblankmgcbstartkit, project: mgblankmgcbstartkit1.csproj, folder: mgblankmgcbstartkit1, run: true }
        include:
          - os: windows-latest
            platform: windows
            shell: pwsh
          - os: macos-15
            platform: macos
            shell: bash
          - os: ubuntu-24.04
            platform: linux
            shell: bash
            prefix: timeout 5s xvfb-run -a -s "-screen 0 1024x768x24"
          - os: ubuntu-24.04-arm
            platform: linux
            shell: bash
            prefix: timeout 5s xvfb-run -a -s "-screen 0 1024x768x24"
        exclude:
          - os: ubuntu-24.04-arm
            template: { id: mgwindowsdx, name: WindowsDX, short: mgwindowsdx, project: mgwindowsdx1.csproj, folder: mgwindowsdx1, run: true }
          - os: ubutnu-24.04-arm
            template: { id: mg2dstartkit, name: MonoGame 2D StartKit, short: mg2dstartkit, project: mg2dstartkit1.csproj, folder: mg2dstartkit1, run: true }
          - os: ubuntu-24.04
            template: { id: mgwindowsdx, name: WindowsDX, short: mgwindowsdx, project: mgwindowsdx1.csproj, folder: mgwindowsdx1, run: true }
          - os: ubutnu-24.04
            template: { id: mg2dstartkit, name: MonoGame 2D StartKit, short: mg2dstartkit, project: mg2dstartkit1.csproj, folder: mg2dstartkit1, run: true }
          - os: macos-15
            template: { id: mgwindowsdx, name: WindowsDX, short: mgwindowsdx, project: mgwindowsdx1.csproj, folder: mgwindowsdx1, run: true }
      fail-fast: false
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - name: Download Nuget Packages
        uses: actions/download-artifact@v4
        with:
          name: MonoGame.Templates.CSharp.${{ ENV.TEMPLATE_VERSION }}
          path: nugets
      - name: Setup .NET 8.0.x & 9.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            8.0.x
            9.0.x
            10.0.x
      - name: Install .net Android
        run: |
          dotnet workload install android --skip-manifest-update
      - name: Install .net iOS
        if: ${{ matrix.os == 'macos-15' || matrix.os == 'windows-latest' }} 
        run: |
          dotnet workload install ios --skip-manifest-update
      - name: Setup Wine
        uses: monogame/monogame-actions/install-wine@v1

      - name: Install Fonts
        uses: monogame/monogame-actions/install-fonts@v1

      - name: Install Templates
        run: |
          dotnet new install nugets/Release/MonoGame.Templates.CSharp.${{ ENV.TEMPLATE_VERSION }}.nupkg

      - name: Create and build ${{ matrix.template.name }}
        run: |
          mkdir -p ${{ matrix.template.folder }}
          cd ${{ matrix.template.folder }}
          dotnet new ${{ matrix.template.short }} ${{ matrix.template.args }}
          dotnet tool restore
          dotnet build
        env:
          MGFXC_WINE_PATH=/home/runner/.winemonogame
          DOTNET_SYSTEM_NET_SECURITY_NOREVOCATIONCHECKBYDEFAULT: 1 # android compilation is failing randomly due to downloads from microsofts website during it

      - name: Run ${{ matrix.template.name }}
        if: ${{ matrix.template.run && startsWith(matrix.os, 'ubuntu-') }}
        run: |
          cd ${{ matrix.template.folder }}
          set +e
          ${{ matrix.prefix }} dotnet run --project ${{ matrix.template.project }}
          exit_code=$?

          # timeout -> success (app stayed alive for smoke-test window)
          if [ "$exit_code" -eq 124 ]; then
            echo "Smoke run passed: timed out as expected."
            exit 0
          fi

          # any other code is a real failure (or unexpected early exit)
          echo "Smoke run failed with exit code $exit_code"
          exit "$exit_code"
        env:
          MGFXC_WINE_PATH=/home/runner/.winemonogame
          DOTNET_SYSTEM_NET_SECURITY_NOREVOCATIONCHECKBYDEFAULT: 1 # android compilation is failing randomly due to downloads from microsofts website during it