name: Visual Studio Project Templates
env:
  TEMPLATE_VERSION: 3.8.4.1

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-vscode:
    runs-on: windows-latest
    name: Build Templates
    
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v4
      with:
        path: main
        submodules: true

    - name: Setup .NET 8.0.x & 9.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          8.0.x
          9.0.x

    - name: Build and Pack the Templates into a NUGET
      id: MG-Templates
      run: dotnet pack main/CSharp/MonoGame.Templates.CSharp.csproj -p:Configuration=Release /p:Version=${{ ENV.TEMPLATE_VERSION }}

    - name: Upload Template Nugets
      uses: actions/upload-artifact@v4
      with:
        name: MonoGame.Templates.CSharp.${{ ENV.TEMPLATE_VERSION }}
        path: 'Artifacts/MonoGame.Templates.CSharp/**/*.nupkg'

  test-templates:
    needs: [ build-vscode ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # - os: windows${{ needs.choose-runner.outputs.runner }}latest
          #   platform: windows
          #   shell: pwsh
          # - os: macos${{ needs.choose-runner.outputs.runner }}15
          #   platform: macos
          #   shell: bash
          - os: ubuntu-24.04
            platform: linux
            shell: bash
            prefix: xvfb-run -a -s "-screen 0 1024x768x24"
          - os: ubuntu-24.04-arm
            platform: linux
            shell: bash
            prefix: xvfb-run -a -s "-screen 0 1024x768x24"
      fail-fast: false
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - name: Download Nuget Packages
        uses: actions/download-artifact@v4
        with:
          name: MonoGame.Templates.CSharp.${{ ENV.TEMPLATE_VERSION }}
          path: nugets
      - name: Check Nugets
        run: |
          find nugets
      - name: Setup .NET 8.0.x & 9.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            8.0.x
            9.0.x
            10.0.x
      - name: Install Templates
        run: |
          dotnet new install nugets/Release/MonoGame.Templates.CSharp.${{ ENV.TEMPLATE_VERSION }}.nupkg